### ISSUE TITLE
Ability to get all queue managers' names on a server into a list

### ISSUE THREAD

**Issue by kengay21** [ibm-messaging/mq-ansible#103]
**Is your feature request related to a problem? Please describe.**

Yes.  It's very common to have several queue managers running or defined (even if running else where) on a server. One shouldn't have to know the names of the queue managers defined on a server to be able to action them - start (running), stop (stopped), or delete(absent).   In fact, having to know the names, somewhat defeats the automation utility and solution that Ansible provides.

**Describe the solution you'd like**

The "**dspmq**" command will list all queue managers defined on a server.  The "regex_search" command can be used to loop through the output of the "**dspmq**" command and retrieve all queue managers' name into an Ansible list.  That list can then be assigned to the "**qmname**" parm of any of the functions in **queue_manager** module.  The main reason for this enhancement is that not everyone knows Ansible **regex_search** command well enough to extract a queue manager name with only the permissible  characters allowed by IBM MQ.  This enhancement will alleviate the need for them to have in-depth and detailed knowledge of **regex_search** command to get the queue managers' name in a list.  The only time the queue manager(s) name need to be explicitly listed, is when a queue manager is being created (present) or when action is needed on only a specific subset of the queue managers.  Usually during patching, upgrade, and un-installation of MQ, all queue managers must be stopped, and in the case of un-installation, stopped and deleted.  This is where the enhancement will be very useful.

**Describe alternatives you've considered**

**None**

**Additional context**

**Comment by JamRamPage** [comment]
Once #100 is fixed and merged, I have code that should get this working.
