### ISSUE TITLE
Logic for mqsc_file and state:stopped

### ISSUE THREAD

**Issue by JamRamPage** [ibm-messaging/mq-ansible#13]
Currently, the queue_manager module does not handle the logic for running some MQSC, then stopping the queue manager in one command. This is a rarer use case, but still one which Customers would appreciate. For example, running MQSC to suspend a Queue Manager from a cluster, before stopping the queue manager: 

https://community.ibm.com/community/user/integration/discussion/mq-pluginmodules-for-ansible#bm3f776585-09bb-4bf8-a16f-018597cc2e3e

I have performed some basic tests to verify this - it appears that we do process the MQSC file, but do not then subsequently issue the endmqm command to stop the qmgr (see in Picture 3, the QMGR is still running).
![image.png](https://zenhub.ibm.com/images/5f2bf1d8ac5aa50ef099048d/75f3487b-4bc3-433e-9d2f-7684933b7b9c)
![image.png](https://zenhub.ibm.com/images/5f2bf1d8ac5aa50ef099048d/d1c88575-9595-45ee-8362-18ff3adeb85b)
![image.png](https://zenhub.ibm.com/images/5f2bf1d8ac5aa50ef099048d/d56b7dea-fa4e-4da3-ae8e-207a3de99d2d)

This should be quite an easy change to the queue_manager module.

**Comment by JamRamPage** [comment]
@stewmcl Did you make a PR addressing this before?

**Comment by stewmcl** [comment]
Thought I had made a PR addressing this.. i'll have a look into it
