### ISSUE TITLE
Read from local MQSC file

### ISSUE THREAD

**Issue by JamRamPage** [ibm-messaging/mq-ansible#17]
The MQSC file used by the queue_manager module is currently read from the target machine (assuming it has already been copied there during installation, or with a suitable playbook). 

The Ansible module runs on the target machine, so it is unlikely that we can read from the host from within the python code.

Instead, a custom MQSC configuration can be moved to any desired target machines using the ansible.builtin.copy module (https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html).

We may wish to document this, or integrate it directly with our sample playbooks.

**Comment by bimsara-yasitha01** [comment]
I belive as of now, this issue can be closed out. A local MQSC file on the host is copied to the target machine, which is then read and executed from a specified location on the target. To my knowledge, this has always been the design - but please correct me if I have misunderstood.
