### ISSUE TITLE
downloadmq Idempotency

### ISSUE THREAD

**Issue by JamRamPage** [ibm-messaging/mq-ansible#20]
Currently the role downloadmq works successfully, however on a machine which already has MQ installed, this role runs _again_, which takes a considerable length of time to complete.

Maintaining idempotency with the ibmmq.yml (so that repeated execution will not disrupt the install on a machine, but can be used to update certain values), will require:

1. Checking whether the MQ version selected matches one installed.
2. If not, downloading the appropriate version and continuing installing.
3. If so, _skipping this step_ as this will save time - **several minutes per testrun**, depending on your available bandwidth.

**Comment by bimsara-yasitha01** [comment]
This is now fixed following the merge of #29 which changes the MQ download folder to `/var` instead of `/tmp`. The `/tmp` folder is cleared every few days if not accessed so changing to `/var` now keeps this download persistent.
