### ISSUE TITLE
Query / Functionality request

### ISSUE THREAD

**Issue by Syko80** [ibm-messaging/mq-ansible#90]
Can any of the developed explain why in these playbooks the ssh_connection is reset?

https://github.com/ibm-messaging/mq-ansible/blob/main/roles/installmq/tasks/Linux_installmq.yml
https://github.com/ibm-messaging/mq-ansible/blob/main/roles/installmq/tasks/AIX_installmq.yml

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection

I am running the playbook using a bastion.  I have to run a role to establish that bastion connection and this reset command then breaks the connection

So

1) can anyone explain why the reset is done/needed?
2) if it best to be optional, can it be changed to run with a 'when' command and include a variable like 'reset_conn_after_install: true/false ?

**Comment by stewmcl** [comment]
1. The reset was initially done as for certain changes, such as adding a user to a group or applying certain permissions etc.. to take effect to the user, the connection would require a reset. 
2. There are a few alternate ways to do this, potentially by switching user to the current user `su yourself`. We'll have a look at making a change so it doesn't need to reset the connection.

**Comment by stewmcl** [comment]
Should be fixed with #91
